kafka:
  brokers: localhost:9092
  security: false
  truststorePath:
  keystorePath:
  credstorePsw:

søknad:
  name: aap.soknad
  group-id: vilkar-3
  client-id: vilkar-aap.soknad

grunnlag:
  name: aap.grunnlag
  group-id: vilkar-4
  client-id: vilkar-aap.grunnlag

vilkår:
  name: aap.vilkar
  group-id: vilkar-1
  client-id: vilkar-app.vilkar

db:
  url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  username: sa
  password: ""
