services:
  kafka:
    image: wurstmeister/kafka
    depends_on: [ zookeeper ]
    ports: [ 9092:9092 ]
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://:9093,OUTSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_DELETE_TOPIC_ENABLED: "true"
      KAFKA_CREATE_TOPICS: "aap.soknad:2:1,aap.grunnlag:2:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports: [ 2181:2181 ]

# List records:
#  kcat -b localhost:9092 -t  grunnlag -C
#
# Delete topic:
#  docker exec -it 4b74bcb8aeb0 /bin/sh
#  opt/kafka/bin/kafka-topics.sh -zookeeper zookeeper:2181 --delete --topic soknad-sendt