name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          check-latest: true
      - uses: gradle/wrapper-validation-action@v1
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: test --continue --no-daemon

  topology:
    needs: [ test ]
    uses:  rtc11/poc/.github/workflows/topology.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      actor: ${{ github.actor }}
