name: Generate PlantUML for Kafka Streams Topology

on: [ push ]

jobs:
  plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Process diagrams
        uses: Timmy/plantuml-action@v1
        with:
          args: '-tpng app/kafka-streams-json/topology.puml'
      - uses: actions/upload-artifact@v2
        with:
          name: topology
          path: app/kafka-streams-json/topology.png
